name: Unzip File
on:
  push:
    branches: [ main ]
    paths: [ '*.zip' ]  # 监控ZIP文件变动

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip file
        run: |
          unzip 文件名.zip -d 解压目录/
          rm 文件名.zip  # 可选：删除原ZIP文件
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-unzip file"
          git push
